In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
dataset = pd.read_csv("/content/datasets_4458_8204_winequality-red (2).csv")

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [5]:
dataset['quality'].unique()

array([5, 6, 7, 4, 8, 3])

In [6]:
X = dataset.iloc[: , 1:-1].values
y = dataset.iloc[:, -1].values

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X ,y, test_size=0.20)

In [9]:
from sklearn.preprocessing import StandardScaler

In [11]:
sc = StandardScaler()

In [12]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [14]:
l_cla = LogisticRegression()
k_cla = KNeighborsClassifier()
d_cla = DecisionTreeClassifier()
r_cla = RandomForestClassifier()
s_cla = SVC(kernel='linear')
ks_cla = SVC(kernel= 'rbf')

In [15]:
l_cla.fit(X_train, y_train)
k_cla.fit(X_train, y_train)
d_cla.fit(X_train, y_train)
r_cla.fit(X_train, y_train)
s_cla.fit(X_train, y_train)
ks_cla.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [16]:
SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [17]:
l_pred = l_cla.predict(X_test)
k_pred = k_cla.predict(X_test)
d_pred = d_cla.predict(X_test)
r_pred = r_cla.predict(X_test)
s_pred = s_cla.predict(X_test)
ks_pred = ks_cla.predict(X_test)

In [18]:
from sklearn.metrics import confusion_matrix

In [19]:
l_c = confusion_matrix(y_test, l_pred)
k_c = confusion_matrix(y_test, k_pred)
d_c = confusion_matrix(y_test, d_pred)
r_c = confusion_matrix(y_test, r_pred)
s_c = confusion_matrix(y_test, s_pred)
ks_c = confusion_matrix(y_test, ks_pred)

In [20]:
l_c

array([[  0,   8,   2,   0,   0],
       [  1, 101,  23,   1,   0],
       [  1,  46,  81,   7,   0],
       [  0,   3,  31,  14,   0],
       [  0,   0,   1,   0,   0]])

In [21]:
k_c

array([[ 0,  8,  2,  0,  0],
       [ 1, 88, 31,  5,  1],
       [ 2, 41, 86,  6,  0],
       [ 0,  3, 27, 18,  0],
       [ 0,  0,  1,  0,  0]])

In [22]:
d_c

array([[ 0,  9,  1,  0,  0],
       [ 6, 88, 30,  2,  0],
       [ 6, 32, 80, 15,  2],
       [ 0,  3, 14, 29,  2],
       [ 0,  0,  0,  1,  0]])

In [23]:
r_c

array([[  0,   7,   3,   0,   0],
       [  1, 106,  18,   1,   0],
       [  0,  32,  95,   7,   1],
       [  0,   2,  22,  24,   0],
       [  0,   0,   1,   0,   0]])

In [24]:
s_c


array([[  0,   8,   2,   0,   0],
       [  0, 100,  26,   0,   0],
       [  0,  50,  85,   0,   0],
       [  0,   4,  44,   0,   0],
       [  0,   0,   1,   0,   0]])

In [25]:
ks_c

array([[  0,   9,   1,   0,   0],
       [  0, 102,  22,   2,   0],
       [  0,  47,  84,   4,   0],
       [  0,   3,  35,  10,   0],
       [  0,   0,   1,   0,   0]])

In [26]:
from sklearn.metrics import accuracy_score

In [27]:
l_a = accuracy_score(y_test, l_pred)
k_a = accuracy_score(y_test, k_pred)
d_a = accuracy_score(y_test, d_pred)
r_a = accuracy_score(y_test, r_pred)
s_a = accuracy_score(y_test, s_pred)
ks_a = accuracy_score(y_test, ks_pred)

In [28]:
print('Logistic Regression: ' + str(l_a) + '\nKNN: ' + str(k_a) + '\nDecision Tree: ' + str(d_a) + '\nRandom Forest: ' + str(r_a) + '\nLinear SVC: ' + str(s_a) + '\nKernel SVC: ' + str(l_a))

Logistic Regression: 0.6125
KNN: 0.6
Decision Tree: 0.615625
Random Forest: 0.703125
Linear SVC: 0.578125
Kernel SVC: 0.6125
